apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfmshop-deployment
  labels:
    app: sfmshop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sfmshop
  template:
    metadata:
      labels:
        app: sfmshop
    spec:
      containers:
        - name: sfmshop
          image: sfmshop:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: sfmshop
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sfmshop-secret
                  key: DB_PASSWORD
            - name: REDIS_HOST
              value: redis
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
